
user_list:
  path: /api/v1/users
  controller: App\Controller\UserController::list
  methods: GET

user_get:
  path: /api/v1/user/{userId}
  controller: App\Controller\UserController::fetch
  methods: GET
  requirements:
    userId: '\d+'

user_create:
  path: /api/v1/user
  controller: App\Controller\UserController::create
  methods: POST

user_delete:
  path: /api/v1/user/{userId}
  controller: App\Controller\UserController::delete
  methods: DELETE
  requirements:
    userId: '\d+'
